### ISSUE TITLE
Pull request for final capstone's project Kanban board

### ISSUE THREAD

**Issue by agneta1991** [agneta1991/book-an-appointment-capstone#20]
# Pull request for Kanban board

_**Link to the Kanban board below**_
https://github.com/agneta1991/book-an-appointment-capstone/projects/1

**There are 5 people participating in the final capstone project:**
Agneta Pupienyte
Bhekisile Jozi
Ikonde Nekemiah
Yousef Badr
Bwambale Benny Wolter

![kanban](https://github.com/agneta1991/book-an-appointment-capstone/assets/120168752/00a54810-04aa-4e6d-9e0a-de75543ab46a)

**Comment by Meltrust** [comment]
## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
